sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gfortran-4.9 
      - exuberant-ctags
      - libboost-all-dev
      - libplplot-dev
      - libboost-filesystem-dev
      - valgrind
      - ncurses-dev


before_install:
  - git submodule update --init --recursive


script: 
  - g++-4.9 --version
  - TOOL_CHAIN=TRAVIS make 
  - TOOL_CHAIN=TRAVIS make memtest
  - TOOL_CHAIN=TRAVIS make clean
  - TOOL_CHAIN=TRAVIS make cover
  
after_success:
  - cd exports/objs/
  - coveralls --gcov gcov-4.9 --verbose 

