before_install:
  - git submodule update --init --recursive
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8;
  - sudo apt-get install -qq gfortran-4.8
  - sudo apt-get install exuberant-ctags
  - sudo apt-get install libboost-dev
  - sudo apt-get install -qq libboost-dev
  - sudo apt-get install -qq libboost-regex-dev
  - sudo apt-get install libplplot-dev
  - sudo apt-get install libboost-filesystem-dev
  - sudo apt-get install valgrind
  - sudo apt-get install p7zip-full
  - sudo apt-get install libgtk2.0-dev
  - sudo apt-get install libgl1-mesa-dev-lts-trusty
  - sudo apt-get install ncurses-dev
  - sudo apt-get install libudev-dev
  - sudo pip install cpp-coveralls --use-mirrors

script: 
  - g++-4.8 --version
  - ./getCEF.sh
  - LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH CEF_DIR=$PWD/CEF_3.2/cef_binary_3.2171.1979_linux64/ TOOL_CHAIN=TRAVIS make 
  - LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH CEF_DIR=$PWD/CEF_3.2/cef_binary_3.2171.1979_linux64/ TOOL_CHAIN=TRAVIS make memtest
  - CEF_DIR=$PWD/CEF_3.2/cef_binary_3.2171.1979_linux64/ TOOL_CHAIN=TRAVIS make clean
  - LD_LIBRARY_PATH=$PWD:$LD_LIBRARY_PATH CEF_DIR=$PWD/CEF_3.2/cef_binary_3.2171.1979_linux64/ TOOL_CHAIN=TRAVIS make cover
after_success:
  - cd exports/objs/
  - coveralls --gcov gcov-4.8 --verbose 

